### ISSUE TITLE
Error: Cannot find module './libs/PinyinHelper'

### ISSUE THREAD

**Issue by asd1245dss** [superbiger/pinyin4js#1]
`https://npm.runkit.com/pinyin4js`官网的demo运行报错，我本地执行也是报这个错
![image](https://user-images.githubusercontent.com/2149974/27067627-5caa9f00-503e-11e7-9c0a-45f13a7188f3.png)

**Comment by superbiger** [comment]
谢谢提交啊，我回去看下！这段时间太忙了……

**Comment by superbiger** [comment]
这个建议自己build一下看看

**Comment by superbiger** [comment]
已解决
