### ISSUE TITLE
有数字或英文时第二个参数没有添加

### ISSUE THREAD

**Issue by wangguangyou** [superbiger/pinyin4js#13]
有数字或英文时第二个参数没有添加
pinyin4js.convertToPinyinString( '1q好', '#', pinyin4js.WITHOUT_TONE)
//1q#好
//期望1#q#好

**Comment by Kaifuny** [comment]
@wangguangyou 这个建议自行处理好在转移拼音，因为有些时候是不需要数字分割的

**Comment by Kaifuny** [comment]
nothing
