### ISSUE TITLE
在antd-prod上引用（react版本）

### ISSUE THREAD

**Issue by ruby99999** [superbiger/pinyin4js#7]
import  PinyinHelper from 'pinyin4js';
 console.log(PinyinHelper.convertToPinyinString('厦门你好大厦厦门'));

报问题：×
TypeError: __WEBPACK_IMPORTED_MODULE_19_pinyin4js___default.a.convertToPinyinString is not a function

**Comment by superbiger** [comment]
@ruby99999 
有试过直接 import 'pinyin4js' 这种可以吗？

**Comment by ruby99999** [comment]
> @ruby99999
> 有试过直接 import 'pinyin4js' 这种可以吗？

试过还是有问题

**Comment by zhuangxiaohui** [comment]
我是这样用的
```
var Pinyin = require('pinyin4js/lib/PinyinHelper')
var PinyinHelper = Pinyin.PinyinHelper
var PinyinFormat = Pinyin.PinyinFormat
```
建议支持 以下写法
```
 import pinyin4js from  'pinyin4js' 
pinyin4js .convertToPinyinString("测试")
```

**Comment by superbiger** [comment]
😯good idea
